CREATE TABLE GEDITS (
    PID INT,
    DOCID INT,
    ISSUE_NO INT,
    PRIMARY KEY (PID, DOCID, ISSUE_NO),
    FOREIGN KEY (PID) REFERENCES PERSON(PID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (DOCID, ISSUE_NO) REFERENCES JOURNAL_ISSUE(DOCID, ISSUE_NO) ON UPDATE CASCADE ON DELETE CASCADE
);
