CREATE TABLE BORROWS (
    BOR_NO INT,
    DOCID INT,
    COPYNO INT,
    BID INT,
    RID INT,
    PRIMARY KEY (BOR_NO, DOCID, COPYNO, BID),
    FOREIGN KEY (BOR_NO) REFERENCES BORROWING(BOR_NO) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (DOCID, COPYNO, BID) REFERENCES COPY(DOCID, COPYNO, BID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (RID) REFERENCES READER(RID) ON UPDATE CASCADE ON DELETE CASCADE
);
