CREATE TABLE RESERVES (
    RESERVATION_NO INT,
    DOCID INT,
    COPYNO INT,
    BID INT,
    RID INT,
    PRIMARY KEY (RESERVATION_NO, DOCID, COPYNO, BID),
    FOREIGN KEY (RESERVATION_NO) REFERENCES RESERVATION(RES_NO) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (DOCID, COPYNO, BID) REFERENCES COPY(DOCID, COPYNO, BID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (RID) REFERENCES READER(RID) ON UPDATE CASCADE ON DELETE CASCADE
);
