CREATE TABLE AUTHORS (
    PID INT,
    DOCID INT,
    PRIMARY KEY (PID, DOCID),
    FOREIGN KEY (PID) REFERENCES PERSON(PID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (DOCID) REFERENCES DOCUMENT(DOCID) ON UPDATE CASCADE ON DELETE CASCADE
);
