CREATE TABLE COPY (
    DOCID INT,
    COPYNO INT,
    BID INT,
    POSITION VARCHAR(255),
    PRIMARY KEY (DOCID, COPYNO, BID),
    FOREIGN KEY (DOCID) REFERENCES DOCUMENT(DOCID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (BID) REFERENCES BRANCH(BID) ON UPDATE CASCADE ON DELETE CASCADE
);
