CREATE TABLE JOURNAL_ISSUE (
    DOCID INT,
    ISSUE_NO INT,
    SCOPE VARCHAR(255),
    PRIMARY KEY (DOCID, ISSUE_NO),
    FOREIGN KEY (DOCID) REFERENCES JOURNAL_VOLUME(DOCID) ON UPDATE CASCADE ON DELETE CASCADE
);
