CREATE TABLE JOURNAL_VOLUME (
    DOCID INT,
    VOLUME_NO INT,
    EDITOR INT,
    PRIMARY KEY (DOCID, VOLUME_NO),
    FOREIGN KEY (DOCID) REFERENCES DOCUMENT(DOCID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (EDITOR) REFERENCES PERSON(PID) ON UPDATE CASCADE ON DELETE CASCADE
);
